title: Rafe Sharif
subtitle: Academic Portfolio
description: >
  B.Sc. Physics & CS Minor | Computational Astrophysics | Scientific Computing
  Amirkabir University of Technology

url: "https://rafe-sh.github.io"
baseurl: ""
email: rafe.sharif.moghaddam@gmail.com

# Navigation - Single page with anchors
urls:
    - text: Home
      url: /
    - text: About
      url: /#about
    - text: Projects
      url: /#projects
    - text: Publications
      url: /#publications
    - text: Contact
      url: /#contact

# Author Details
author_logo: profile.png
author: Rafe Sharif
author_bio: B.Sc. Physics & CS Minor at AUT | Computational Astrophysics | Scientific Computing
author_email: "rafe.sharif.moghaddam@gmail.com"
author_location: Tehran, Iran
author_website_url: "https://rafe-sh.github.io"

# Social Links
github_username: rafe-sharif
linkedin_username: rafe-sharif
twitter_username: rafe_sharif

# Build Settings - Keep minimal for single HTML file
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - assets/bower_components/
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - SECURITY.md
  - LICENSE
  - .all-contributorsrc
  - .buildconfig
  - .firebaserc
  - .github/
  - .gitignore
  - .ruby-version
  - devlopr.gemspec
  - feed.xml
  - _backup_content/
  - _posts/
  - _products/
  - _authors/
  - _data/
  - _layouts/
  - _includes/
  - _sass/
  - about.md
  - projects.md
  - publications.md
  - cv.md
  - contact.md
